DROP DATABASE IF EXISTS bank CASCADE;
CREATE USER IF NOT EXISTS leader;
CREATE DATABASE bank;
GRANT ALL ON DATABASE bank TO leader;

CREATE TABLE IF NOT EXISTS bank.products (
    id SERIAL,
    name STRING,
    price FLOAT NOT NULL DEFAULT 0.00,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);